# Generated by Django 4.2 on 2023-05-04 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("major", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority1",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=100, unique=True)),
                ("answer", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Priority2",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "question",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("answer", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Priority3",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "question",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("answer", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Apply",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "major",
                    models.ForeignKey(
                        db_column="major",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apply",
                        to="major.major",
                    ),
                ),
                (
                    "priority_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apply_1",
                        to="apply.priority1",
                    ),
                ),
                (
                    "priority_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apply_2",
                        to="apply.priority2",
                    ),
                ),
                (
                    "priority_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apply_3",
                        to="apply.priority3",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apply",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
