# Generated by Django 4.2 on 2023-05-04 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, related_name='apply', to=settings.AUTH_USER_MODEL),
        ),
    ]
