# Generated by Django 4.2.1 on 2023-05-10 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apply", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="user",
            field=models.ForeignKey(
                db_column="user",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apply",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
