# Generated by Django 4.2.1 on 2023-05-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("major", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
            ],
            options={"db_table": "building",},
        ),
        migrations.CreateModel(
            name="Locker",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_share_registered", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("share_start_date", models.DateTimeField(blank=True, null=True)),
                ("share_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "building_id",
                    models.ForeignKey(
                        db_column="building_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locker",
                        to="locker.building",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        db_column="major",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locker",
                        to="major.major",
                    ),
                ),
            ],
            options={"db_table": "locker",},
        ),
    ]
