# Generated by Django 4.2 on 2023-05-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('building_id', models.IntegerField()),
                ('is_share_registered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('share_start_date', models.DateTimeField(blank=True, null=True)),
                ('share_end_date', models.DateTimeField(blank=True, null=True)),
                ('major', models.ForeignKey(db_column='major', on_delete=django.db.models.deletion.PROTECT, related_name='locker', to='major.major')),
            ],
            options={
                'db_table': 'locker',
            },
        ),
    ]
