# Generated by Django 4.2 on 2023-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="apply_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="major",
            name="apply_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
