# Generated by Django 4.2 on 2023-04-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='major',
            table='major',
        ),
    ]
