# Generated by Django 4.2 on 2023-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0002_alter_major_apply_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="priority_first",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
