# Generated by Django 4.2 on 2023-05-04 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("major", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("password", models.TextField()),
                ("penalty", models.BooleanField(default=False)),
                ("penalty_start_date", models.DateTimeField(blank=True, null=True)),
                ("penalty_end_date", models.DateTimeField(blank=True, null=True)),
                ("id_card_img", models.TextField(blank=True, default="")),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "major",
                    models.ForeignKey(
                        db_column="major",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user2",
                        to="major.major",
                    ),
                ),
            ],
            options={"db_table": "user",},
        ),
    ]
