# Generated by Django 4.2 on 2023-04-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.ForeignKey(db_column='major', on_delete=django.db.models.deletion.PROTECT, related_name='major', to='major.major'),
        ),
    ]
