# Generated by Django 4.2 on 2023-05-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_card_img",
            field=models.TextField(blank=True, default=""),
        ),
    ]
