# Generated by Django 4.2 on 2023-04-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('user', '0002_alter_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.ForeignKey(db_column='major', on_delete=django.db.models.deletion.PROTECT, related_name='user', to='major.major'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
